### ISSUE TITLE
Workflow code expects Python 2 interpreter at /usr/bin/python

### ISSUE THREAD

**Issue by thomasd3** [snooze92/alfred-epoch-converter#9] opened 2022-02-05 14:57 UTC
With Alfred 4.6.2, the tool doesn't seem to open anymore.
When I type 'ts', I just get the internet search options.

<img width="531" alt="image" src="https://user-images.githubusercontent.com/14313218/152647000-b138521e-074c-4afc-bdf4-754f6eed0786.png">

while it's properly installed:

<img width="829" alt="image" src="https://user-images.githubusercontent.com/14313218/152647021-c32a454e-7258-4ccd-b96e-1a4b6c5b6d2c.png">

Before the Alfred update, I didn't have that issue.

**Comment by snooze92** [comment] 2022-02-07 09:49
I can't reproduce - the workflow works as expected for me with Alfred 4.6.2:
<img width="800" alt="ts_462" src="https://user-images.githubusercontent.com/3275550/152764353-96c5fbde-46d6-4a5e-96f5-7769e09ff020.png">

Can you provide any more detail? Have you found some log or been able to try anything to fix it?

**Comment by thomasd3** [comment] 2022-02-07 12:37
I just looked at the log and found the issue:

```
13:25:03.736] Logging Started...
[13:25:08.823] Epoch Converter[Script Filter] Queuing argument ''
[13:25:08.838] Epoch Converter[Script Filter] Script with argv '(null)' finished
[13:25:08.840] ERROR: Epoch Converter[Script Filter] Code 127: /bin/bash: /usr/bin/python: No such file or directory
```

while I have the standard files, bundled with MacOS in the /usr/bin folder:

```
/usr/bin ᐅ ll /usr/bin/pyt*
lrwxr-xr-x   85 25 Jan 10:09 /usr/bin/python -> ../../AppleInternal/Library/Frameworks/PythonLegacy.framework/Versions/2.7/bin/python
lrwxr-xr-x   92 25 Jan 10:09 /usr/bin/python-config -> ../../AppleInternal/Library/Frameworks/PythonLegacy.framework/Versions/2.7/bin/python-config
lrwxr-xr-x   86 25 Jan 10:09 /usr/bin/python2 -> ../../AppleInternal/Library/Frameworks/PythonLegacy.framework/Versions/2.7/bin/python2
lrwxr-xr-x   93 25 Jan 10:09 /usr/bin/python2-config -> ../../AppleInternal/Library/Frameworks/PythonLegacy.framework/Versions/2.7/bin/python2-config
lrwxr-xr-x   88 25 Jan 10:09 /usr/bin/python2.7 -> ../../AppleInternal/Library/Frameworks/PythonLegacy.framework/Versions/2.7/bin/python2.7
lrwxr-xr-x   95 25 Jan 10:09 /usr/bin/python2.7-config -> ../../AppleInternal/Library/Frameworks/PythonLegacy.framework/Versions/2.7/bin/python2.7-config
.rwxr-xr-x 167k 25 Jan 10:09 /usr/bin/python3
lrwxr-xr-x   86 25 Jan 10:09 /usr/bin/pythonw -> ../../AppleInternal/Library/Frameworks/PythonLegacy.framework/Versions/2.7/bin/pythonw
lrwxr-xr-x   87 25 Jan 10:09 /usr/bin/pythonw2 -> ../../AppleInternal/Library/Frameworks/PythonLegacy.framework/Versions/2.7/bin/pythonw2
lrwxr-xr-x   89 25 Jan 10:09 /usr/bin/pythonw2.7 -> ../../AppleInternal/Library/Frameworks/PythonLegacy.framework/Versions/2.7/bin/pythonw2.7
```

the symlink doesn't go anywhere:

```
python -> ../../AppleInternal/Library/Frameworks/PythonLegacy.framework/Versions/2.7/bin/python
```

but there is python3 in the folder.

I'm on Monterey 12.3 beta and all the OS files are from Jan 25, so maybe there are some changes going to happen.

What about first letting the shell trying to resolve where python and, it it fails try a few common hardcoded paths?
/usr/bin is one, but also there is the brew path (/usr/local/opt/python/libexec/bin/python).

**Comment by thomasd3** [comment] 2022-02-07 12:42
On another note, the script is not a fan on Python3, it looks like deps would need to be installed for the libs you use. I don't know how the workflows are set up in Alfred and where the dependencies are resolved.

```
  File "epoch.py", line 8, in <module>
    from workflow import Workflow, ICON_CLOCK, ICON_NOTE
  File "/Users/thomas/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.1D19C044-E092-4F41-8DD9-FA26701C7EE2/workflow/__init__.py", line 16, in <module>
    from .workflow import Workflow, manager
  File "/Users/thomas/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.1D19C044-E092-4F41-8DD9-FA26701C7EE2/workflow/workflow.py", line 25, in <module>
    import cPickle
ModuleNotFoundError: No module named 'cPickle'
```

if you need me to run any test, don't hesitate.

**Comment by snooze92** [comment] 2022-02-07 12:49
We are "stuck" on Python 2.7 for this unfortunately, until I or a willing soul has time for a PR to bump to Python 3. ;)

I can confirm that currently, the ts script runs `/usr/bin/python epoch.py "{query}"` (https://github.com/snooze92/alfred-epoch-converter/blob/master/info.plist#L71). I'm on macOS Monterey 12.1, unable to reproduce the issue. Are you able to try a different entrypoint that fixes your issue? You can try different things in the Workflow editor:
<img width="788" alt="ts_editor" src="https://user-images.githubusercontent.com/3275550/152791188-fe553591-df59-4d14-855d-bbf808a9cd7b.png">

**Comment by thomasd3** [comment] 2022-02-07 12:53
I think Python 3 will be inevitable, I found this:

https://macmule.com/2022/01/29/macos-monterey-12-3-will-remove-python-2-7-usr-bin-python/

**Comment by snooze92** [comment] 2022-02-07 12:58
Indeed... but based on https://github.com/deanishe/alfred-workflow/issues/97, I expect it won't be a very straightforward fix unfortunately.

**Comment by thomasd3** [comment] 2022-02-07 13:01
oh, I didn't know that; I'll write Dean to see what's the plan in the light of the upcoming update.

**Comment by 0x-2a** [comment] 2022-03-17 16:49
@snooze92 this worked

First get python 2 back
```shell
# Download/run the legacy macOS installer (pick which one for your sys)
https://www.python.org/downloads/release/python-2716/

# Add pip for python2.7
curl https://bootstrap.pypa.io/pip/2.7/get-pip.py -o get-pip2.py
python2 get-pip2.py

# Add the missing macos plist lib alfred uses
curl https://raw.githubusercontent.com/python/cpython/2.7/Lib/plistlib.py -o /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py

# Add any missing pips (might be unneeded, mine just worked)
python2 -m pip __________

# Optionally add the helpers like easy_install back onto your path
# In your ~/.zprofile or whatever bash/shell profile equivalent
PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"
export PATH
```

Update the script filter to use /usr/**local**/bin instead of /usr/**bin** using one of the options below. If folks come here and don't know where to find this it's in Alfred Prefs > Workflows > double click this square with Script Filter. 

If `which python` shows 2.7
```shell
/usr/local/bin/python epoch.py "{query}"
```

If `which python` shows 3... 
```shell
/usr/local/bin/python2 epoch.py "{query}"
```

For more legacy python2 help I wrote an SO post: https://stackoverflow.com/a/71513250/786389

**Comment by snooze92** [comment] 2022-03-17 19:50
Nice, thanks @y3sh 

I do hope I find the time to make my workflow work with Python 3, we're in 2022 after all! ;)

**Comment by zjn0505** [comment] 2022-03-26 06:27
The change turned out to be quite simple on macOS 12.3.
I just replaced the `workflow` folder with https://github.com/NorthIsUp/alfred-workflow-py3
Then changed the script to `python3 epoch.py "{query}"`

**Comment by andy4222** [comment] 2022-03-27 06:42
It seems to be returning the below error. I just replaced the folder and updated the command to python3. Anything else needs to be done?

`[23:41:06.921] ERROR: dev- Epoch Converter[Script Filter] Code 1: Traceback (most recent call last):
  File "epoch.py", line 10, in <module>
    reload(sys)
NameError: name 'reload' is not defined`

**Comment by iF2007** [comment] 2022-03-29 07:33
After manually installling Python 2 on macOS 12.3 and slightly changed the workflow config (`/usr/local/bin/python2 epoch.py "{query}"`), it works. When I was about to submit an issue, then I came across this..

**Comment by giovannicoppola** [comment] 2022-03-29 20:33
I converted this to Python 3, let me know if you run into any issues! Thanks @snooze92 for making this workflow. 
https://github.com/giovannicoppola/alfred-epoch-converter

**Comment by Kovah** [comment] 2022-03-30 17:23
@giovannicoppola Your version works as expected, maybe this could be merged here?

**Comment by andy4222** [comment] 2022-03-31 00:51
@snooze92 two people have migrated the workflow to python 3, could you please take a look at their PRs and merge?

**Comment by snooze92** [comment] 2022-03-31 00:53
Sure, thanks! I am on holidays until Wed 6 April, will take a look after that ;)

**Comment by snooze92** [comment] 2022-04-11 18:57
So I had a quick look at both PRs and verified the smaller one locally. I think with a few additional minor tweaks that one would work. 🎉 

I replied on https://github.com/snooze92/alfred-epoch-converter/pull/10 and I will merge it soon regardless.

**Closed as completed** 2022-04-12 12:50 UTC

**Comment by snooze92** [comment] 2022-04-12 13:00
I expect [latest](https://github.com/snooze92/alfred-epoch-converter/releases/latest) release (tag [1.0.3](https://github.com/snooze92/alfred-epoch-converter/releases/tag/1.0.3)) fixes the issue for anyone, as long as your macOS system has the expected `/usr/bin/python3` available.

Let me know if any issue is left! ;)
